security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\PlaintextAuthenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard/admin, roles: ROLE_ADMIN }
        - { path: ^/dashboard/psychologue, roles: ROLE_PSYCHOLOGUE }
        - { path: ^/dashboard/patient, roles: ROLE_PATIENT }
        - { path: ^/dashboard, roles: ROLE_USER }  # sécurité générale