<?php

namespace ContainerUiHBomp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6pV6rJJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6pV6rJJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'slugger' => ['privates', '.errored.sBcKH07', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::edit()": the $slugger argument is type-hinted with the non-existent class or interface: "App\\Controller\\SluggerInterface". Did you forget to add a use statement?'],
            'user' => ['privates', '.errored..service_locator.6pV6rJJ.App\\Entity\\Users', NULL, 'Cannot autowire service ".service_locator.6pV6rJJ": it needs an instance of "App\\Entity\\Users" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'slugger' => '?',
            'user' => 'App\\Entity\\Users',
        ]);

        if (isset($container->privates['.service_locator.6pV6rJJ'])) {
            return $container->privates['.service_locator.6pV6rJJ'];
        }

        return $container->privates['.service_locator.6pV6rJJ'] = $instance;
    }
}
