<?php

namespace ContainerUiHBomp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_INEEFiMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iNEEFiM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'slugger' => '?',
        ]);

        if (isset($container->privates['.service_locator.iNEEFiM'])) {
            return $container->privates['.service_locator.iNEEFiM'];
        }

        return $container->privates['.service_locator.iNEEFiM'] = $instance;
    }
}
