<?php

namespace ContainerUiHBomp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Zksvq1bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Zksvq1b' shared service.
     *
     * @return \App\Repository\UserRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\UserController::index()": the $userRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\UserRepository".');
    }
}
