<?php

namespace ContainerUiHBomp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotejourService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xXO.Egm.App\Entity\Notejour' shared service.
     *
     * @return \App\Entity\Notejour
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xXO.Egm": it needs an instance of "App\\Entity\\Notejour" but this type has been excluded in "config/services.yaml".');
    }
}
