<?php

namespace ContainerGQXps1T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QiKjCnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qiKjCn_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'user' => ['privates', '.errored..service_locator.qiKjCn_.App\\Entity\\Users', NULL, 'Cannot autowire service ".service_locator.qiKjCn_": it needs an instance of "App\\Entity\\Users" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'user' => 'App\\Entity\\Users',
        ]);

        if (isset($container->privates['.service_locator.qiKjCn_'])) {
            return $container->privates['.service_locator.qiKjCn_'];
        }

        return $container->privates['.service_locator.qiKjCn_'] = $instance;
    }
}
