<?php

namespace ContainerGQXps1T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1GqD3HhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1GqD3Hh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1GqD3Hh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'notejourRepository' => ['privates', 'App\\Repository\\NotejourRepository', 'getNotejourRepositoryService', true],
        ], [
            'notejourRepository' => 'App\\Repository\\NotejourRepository',
        ]);
    }
}
