<?php

namespace ContainerGQXps1T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Br3_SlbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.br3.Slb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.br3.Slb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'objectif' => ['privates', '.errored..service_locator.br3.Slb.App\\Entity\\Objectif', NULL, 'Cannot autowire service ".service_locator.br3.Slb": it needs an instance of "App\\Entity\\Objectif" but this type has been excluded in "config/services.yaml".'],
        ], [
            'objectif' => 'App\\Entity\\Objectif',
        ]);
    }
}
