<?php

namespace ContainerGQXps1T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S8SPndyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s8SPndy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reclamation' => ['privates', '.errored..service_locator.s8SPndy.App\\Entity\\Reclamation', NULL, 'Cannot autowire service ".service_locator.s8SPndy": it needs an instance of "App\\Entity\\Reclamation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'reclamation' => 'App\\Entity\\Reclamation',
        ]);

        if (isset($container->privates['.service_locator.s8SPndy'])) {
            return $container->privates['.service_locator.s8SPndy'];
        }

        return $container->privates['.service_locator.s8SPndy'] = $instance;
    }
}
