<?php

namespace ContainerGQXps1T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WwQLiAVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WwQLiAV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'objectif' => ['privates', '.errored..service_locator.WwQLiAV.App\\Entity\\Objectif', NULL, 'Cannot autowire service ".service_locator.WwQLiAV": it needs an instance of "App\\Entity\\Objectif" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'objectif' => 'App\\Entity\\Objectif',
        ]);

        if (isset($container->privates['.service_locator.WwQLiAV'])) {
            return $container->privates['.service_locator.WwQLiAV'];
        }

        return $container->privates['.service_locator.WwQLiAV'] = $instance;
    }
}
