<?php

namespace ContainerGQXps1T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PKVWB9sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pKVWB9s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'evaluationService' => ['privates', 'App\\Service\\ObjectiveEvaluationService', 'getObjectiveEvaluationServiceService', true],
        ], [
            'entityManager' => '?',
            'evaluationService' => 'App\\Service\\ObjectiveEvaluationService',
        ]);

        if (isset($container->privates['.service_locator.pKVWB9s'])) {
            return $container->privates['.service_locator.pKVWB9s'];
        }

        return $container->privates['.service_locator.pKVWB9s'] = $instance;
    }
}
