<?php

namespace ContainerGQXps1T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjectiveEvaluationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ObjectiveEvaluationService' shared autowired service.
     *
     * @return \App\Service\ObjectiveEvaluationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ObjectiveEvaluationService.php';

        return $container->privates['App\\Service\\ObjectiveEvaluationService'] = new \App\Service\ObjectiveEvaluationService(($container->privates['App\\Repository\\ObjectifRepository'] ?? $container->load('getObjectifRepositoryService')), ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('default::AI_API_URL'), $container->getEnv('default::AI_API_KEY'), $container->getEnv('default:0:AI_ENABLED'));
    }
}
