<?php

namespace ContainerGQXps1T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsers3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qiKjCn_.App\Entity\Users' shared service.
     *
     * @return \App\Entity\Users
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qiKjCn_": it needs an instance of "App\\Entity\\Users" but this type has been excluded in "config/services.yaml".');
    }
}
