<?php

namespace ContainerPdB1GDF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LOgV2hxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lOgV2hx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'slugger' => ['privates', '.errored.xKrDrtZ', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::new()": the $slugger argument is type-hinted with the non-existent class or interface: "App\\Controller\\SluggerInterface". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'slugger' => '?',
        ]);

        if (isset($container->privates['.service_locator.lOgV2hx'])) {
            return $container->privates['.service_locator.lOgV2hx'];
        }

        return $container->privates['.service_locator.lOgV2hx'] = $instance;
    }
}
