<?php

namespace ContainerPdB1GDF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RlsOlm3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RlsOlm3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'notejourRepository' => ['privates', 'App\\Repository\\NotejourRepository', 'getNotejourRepositoryService', true],
        ], [
            'entityManager' => '?',
            'notejourRepository' => 'App\\Repository\\NotejourRepository',
        ]);

        if (isset($container->privates['.service_locator.RlsOlm3'])) {
            return $container->privates['.service_locator.RlsOlm3'];
        }

        return $container->privates['.service_locator.RlsOlm3'] = $instance;
    }
}
