<?php

namespace ContainerPdB1GDF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_XKrDrtZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.xKrDrtZ' shared service.
     *
     * @return \App\Controller\SluggerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\UserController::new()": the $slugger argument is type-hinted with the non-existent class or interface: "App\\Controller\\SluggerInterface". Did you forget to add a use statement?');
    }
}
