<?php

namespace ContainerPdB1GDF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjectifService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WwQLiAV.App\Entity\Objectif' shared service.
     *
     * @return \App\Entity\Objectif
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.WwQLiAV": it needs an instance of "App\\Entity\\Objectif" but this type has been excluded in "config/services.yaml".');
    }
}
