<?php

namespace ContainerPdB1GDF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0488DqB.App\Entity\Reponse' shared service.
     *
     * @return \App\Entity\Reponse
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0488DqB": it needs an instance of "App\\Entity\\Reponse" but this type has been excluded in "config/services.yaml".');
    }
}
