<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPdB1GDF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPdB1GDF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPdB1GDF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPdB1GDF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPdB1GDF\App_KernelDevDebugContainer([
    'container.build_hash' => 'PdB1GDF',
    'container.build_id' => 'ac30a250',
    'container.build_time' => 1776526596,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPdB1GDF');
