<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUiHBomp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUiHBomp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUiHBomp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUiHBomp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUiHBomp\App_KernelDevDebugContainer([
    'container.build_hash' => 'UiHBomp',
    'container.build_id' => '1833b7fb',
    'container.build_time' => 1776532018,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUiHBomp');
